meta_product_name: "Poke"
meta_title: "Poke - One shot to break the ice"
meta_description: "Poke is your one chance to find your dream date! It makes first impressions easy, stress free, more fun and totally unique! You get one shot to poke and dazzle your interest! Make it count!"
meta_image: "poke-facebook.png" # should exist in `app/assets/images/`
